# Generated by Django 4.2.7 on 2023-11-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie1app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='exit', upload_to='gallary'),
            preserve_default=False,
        ),
    ]
